# Generated by Django 5.2.7 on 2025-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_psicologo_apellido_psicologo_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('cv', models.FileField(blank=True, null=True, upload_to='solicitudes_cv/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
