# Generated by Django 5.2.7 on 2025-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solicitudpsicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
