# Generated by Django 5.2.7 on 2025-11-20 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solicitudpsicologo_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='especialidad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='titulo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
