# Generated by Django 5.2.7 on 2025-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_psicologo_apellido_remove_psicologo_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpsicologo',
            name='cv_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
