# Generated by Django 5.2.7 on 2025-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_solicitudpsicologo_cv_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpsicologo',
            name='cv_name',
        ),
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.TextField(),
        ),
    ]
