# Generated by Django 5.2.7 on 2025-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_solicitudpsicologo_cv_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.TextField(max_length=1024),
        ),
    ]
