# Generated by Django 5.2.7 on 2025-11-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_solicitudpsicologo_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpsicologo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='solicitudpsicologo',
            name='telefono',
        ),
        migrations.AddField(
            model_name='solicitudpsicologo',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
