# Generated by Django 5.2.7 on 2025-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_solicitudpsicologo_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpsicologo',
            name='cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
