# Generated by Django 5.2.7 on 2025-11-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_solicitudpsicologo_cv'),
    ]

    operations = [
    ]
