# Generated by Django 5.2.7 on 2025-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20251125_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
