# Generated by Django 5.2.7 on 2025-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_psicologo_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpsicologo',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
