# Generated by Django 5.2.7 on 2025-11-25 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_solicitudpsicologo_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='consulta',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
