# Generated by Django 5.2.7 on 2025-12-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_paciente_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='recurso',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
