# Generated by Django 5.2.7 on 2025-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_diarioemocional_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarioemocional',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
