# Generated by Django 5.2.7 on 2025-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_diarioemocional_fecha'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consulta',
            name='unique_consulta_psicologo_fecha',
        ),
        migrations.AddField(
            model_name='consulta',
            name='razon_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
